// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bspqtzpgowwpuhlyvszb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcHF0enBnb3d3cHVobHl2c3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDgyMTksImV4cCI6MjA2NTI4NDIxOX0.F4KpY55u3A50j_1GfQvrtjfR-kyPi48_x7ijajyGq6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);